const MultiPeerActionTypes = {
  INIT: 'INIT',
  BROWSE: 'BROWSE',
  STOP_BROWSE: 'STOP_BROWSE',
  DISCONNECT: 'DISCONNECT',
  ADVERTISE: 'ADVERTISE',
  HIDE: 'HIDE',
  INVITE: 'INVITE',
  RESPONSE_INVITE: 'RESPONSE_INVITE',
  CREATE_STREAM_FOR_PEER: 'CREATE_STREAM_FOR_PEER',
  SEND_DATA: 'SEND_DATA',
  BROADCAST_DATA: 'BROADCAST_DATA',
  ON_PEER_FOUND: 'ON_PEER_FOUND',
  ON_PEER_LOST: 'ON_PEER_LOST',
  ON_PEER_CONNECTED: 'ON_PEER_CONNECTED',
  ON_PEER_CONNECTING: 'ON_PEER_CONNECTING',
  ON_PEER_DISCONNECTED: 'ON_PEER_DISCONNECTED',
  ON_STREAM_OPENED: 'ON_STREAM_OPENED',
  ON_INVITE_RECEIVED: 'ON_INVITE_RECEIVED',
  ON_DATA_RECEIVED: 'ON_DATA_RECEIVED',
};

export default MultiPeerActionTypes;
